### ISSUE TITLE
java.lang.RuntimeException: org.apache.hc.core5.http.NoHttpResponseException: api.postmarkapp.com:443 failed to respond

### ISSUE THREAD

**Issue by nogibi** [ActiveCampaign/postmark-java#67]
**Describe the bug**
I'm facing a random error of `api.postmarkapp.com:443 failed to respond`, sometimes `error Broken pipe` on client.deliverMessage.

So far, there have been about ~60 errors out of ~450 calls. If I retry 1-2 times, it works. Here is the stack trace:

```
Caused by: org.apache.hc.core5.http.NoHttpResponseException: api.postmarkapp.com:443 failed to respond
	at org.apache.hc.core5.http.impl.io.DefaultHttpResponseParser.createConnectionClosedException(DefaultHttpResponseParser.java:87)
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:243)
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:298)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:596)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:219)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:181)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:200)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:143)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:117)
	at com.postmarkapp.postmark.client.HttpClient.execute(HttpClient.java:90)
	at com.postmarkapp.postmark.client.HttpClientHandler.execute(HttpClientHandler.java:61)
	at com.postmarkapp.postmark.client.ApiClient.deliverMessage(ApiClient.java:67)
	at io.nunchuk.notification.service.email.PostMarkAppEmailSenderImpl.send(PostMarkAppEmailSenderImpl.java:44)
	... 4 common frames omitted
```

**To Reproduce**
Provide steps to reproduce the behavior:
1. Initialise account or server api client
2. Prepare data to send with the request
3. Execute request with data

**Expected behavior**
Not throwing exceptions

**Java (please complete the following information):**
 ```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
 - Environment used: Linux

**Comment by nogibi** [comment]
Updating from 1.11.0 to 1.11.1 seems to have fixed the issue.
